package com.slemenceu.taptrackpc.taptrack.domain.models

data class ServerConfig(
    val ip: String,       // The PC's address on the local Wi-Fi (e.g., "192.168.1.15")
    val port: Int,       // The TCP port the server is listening on (9998)
    val passcode: String // The 4-digit security code generated by the PC
)
